### ISSUE TITLE
Moodle 4.1 - what version of mod_pcast?

### ISSUE THREAD

**Issue by slaudel** [sbourget/moodle-mod_pcast#10]
Running Moodle 4.1 I would like to ask, which commit should I use?
Would you mind, tagging the release commits of mod_pcast for Moodle 4.1?

**Comment by sbourget** [comment]
https://github.com/sbourget/moodle-mod_pcast/releases/tag/v4.1

**Comment by sbourget** [comment]
Tagged releases for Moodle 4.1 & 4.2
