### ISSUE TITLE
Cannot select 'Passing grade' as the criteria for Default activity completion

### ISSUE THREAD

**Issue by drachels** [sbourget/moodle-mod_pcast#12]
In Moodle 4.3 with Podcast version "4.2 (2023041800)" with debug turned on, you should see the following along with possibly some others when you go to a course More > Completion settings and then Default activity completion:

Custom completion rule completionepisodesgroup of module pcast has wrong suffix and has been removed from the form. This has to be fixed by the developer

    line 126 of /completion/classes/edit_base_form.php: call to debugging()
    line 146 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_custom_completion()
    line 178 of /completion/classes/form/form_trait.php: call to core_completion_edit_base_form->add_completion_rules()
    line 247 of /completion/classes/edit_base_form.php: call to core_completion_edit_base_form->add_completion_elements()
    line 118 of /completion/classes/defaultedit_form.php: call to core_completion_edit_base_form->definition()
    line 217 of /lib/formslib.php: call to core_completion_defaultedit_form->definition()
    line 45 of /completion/classes/defaultedit_form.php: call to moodleform->__construct()
    line 89 of /course/classes/output/bulk_activity_completion_renderer.php: call to core_completion_defaultedit_form->__construct()
    line 97 of /course/defaultcompletion.php: call to core_course_bulk_activity_completion_renderer->defaultcompletion()

**Comment by drachels** [comment]
I had this same problem with my own plugins and had to add the suffix's to the public function add_completion_rules in the mod_form.php file. So far I've done HotQuestion and MooTyper. Still trying to decide if I need extra completion requirements for Diary.

**Comment by sbourget** [comment]
Thanks for the report and the fix.  I've pushed the fix, and once GHA has confirmed that I didn't break anything in Behat, I'll publish a new version to the Plugins DB.

**Comment by drachels** [comment]
I wish I could work that fast. My biggest problem is that the PHP language was not even invented when I was going to college and learning how to program in about a dozen programming languages. Seems to take me forever, for instance when I was fixing suffix's I think it took me two days to do them for HotQuestion and MooTyper and I am dragging my feet when it comes to the Diary plugin, because I also need to add five more custom completion settings, plus some other stuff.
